name: Build and Deploy

# Trigger the workflow on push to the main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub (if using DockerHub, for GHCR replace with GHCR login)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build the Docker image and tag it with latest and with the commit SHA
      - name: Build the Docker image
        run: |
          docker build . -t ddesmond/img-restoration:latest -t ddesmond/img-restorarion:${{ github.sha }}

      # Step 5: Push the Docker image to DockerHub (replace this with GHCR if using GitHub Container Registry)
      - name: Push Docker image
        run: |
          docker push ddesmond/img-restorarion:latest
          docker push ddesmond/img-restorarion:${{ github.sha }}
